# Generated by Django 5.2 on 2025-04-16 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('summary', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modify', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['title', 'is_active', 'pub_date', 'last_modify'], name='posts_post_title_00fbbe_idx')],
            },
        ),
    ]
